### ISSUE TITLE
Remove the :PROPERTIES: header in org-roam files

### ISSUE THREAD

**Issue by Vidianos-Giannitsis** [brunoarine/org-similarity#1]
Hello,

I am trying out org-similarity and noticed that when running the command in an org-roam file, all the links get the title :PROPERTIES: (which is the first line of the file). This is rather annoying and I would love if a fix was implemented so it ignores :PROPERTIES: headers.

I would be happy to do this myself, but all the important code is in Python and I don't know enough Python to modify the code accordingly. In Elisp, you can work around this by reading the buffer from the 4th line and down to skip the :PROPERTIES: header. This can be done in multiple ways, with the easiest one being `buffer-substring` imo. Or even completely skip reading the first line and grab the title with `org-roam-node-title`. However, I have no clue how this could be implemented inside your python script.

Thanks a lot, I really like the idea of this package, but this behavior is certainly pretty annoying for me.

**Comment by Vidianos-Giannitsis** [comment]
Never mind, I found a solution on stack overflow because luckily python is very popular and most problems are well documented.

Solution if anyone else is interested
Instead of running open in the filename and readline() on that, you can run readlines() instead and then take the third element of the array it returns, which is the 4th line of the document.

**Comment by brunoarine** [comment]
Thanks for the heads up, @Vidianos-Giannitsis ! When I implemented `org-similarity` back then, I didn't predict using it with org files that contained the properties drawer. They were very rare, at least in my workflow.

The scenario has changed significantly since the introduction of `org-roam` v2 and its extensive use of IDs. Therefore, I think `org-similarity` deserves an upgrade in its functionality. I have plans to refactor it as soon as possible.

**Comment by brunoarine** [comment]
Issue fixed with the v0.2 release.
